from pathlib import Path
import json,hashlib,datetime,subprocess
P=Path('/root/projects/UC_Treatment_Recovery');O=P/'runs/001D_annotation'
def record(f):
 p=P/f;return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
old=P/'signature_lock.json';archive=P/'planning/signature_lock_v1.0.json'
if not archive.exists():archive.write_bytes(old.read_bytes())
lock=json.loads(archive.read_text())
lock['version']='1.1';lock['status']='DRAFT_PRE_VALIDATION_AMENDMENT'
lock['supersedes']={'version':'1.0','path':str(archive),'sha256':hashlib.sha256(archive.read_bytes()).hexdigest()}
lock['amendment']={'reason':'User B1-B3 review: common HGNC annotation, invariant inflammation membership across platforms, parallel no-baseline interpretation and comparator/validation-role boundaries','timing':'All discovery outcomes previously observed; GSE23597 and GSE73661 expression not accessed. Public platform annotations and metadata inspected before this amendment. Not a registered report.','validation_expression_accessed':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate_genes_weights_unchanged':True,'old_artifacts_preserved':True}
lock['annotation_rule']=json.loads((O/'annotation_policy.json').read_text())['policy']
genes=[l.split('\t')[0] for l in (O/'frozen_common_inflammation_members.tsv').read_text().splitlines()[1:]]
lock['inflammation_covariate']={'source':'MSigDB Hallmark inflammatory response 2025.1.Hs, canonicalized using frozen HGNC snapshot','genes':genes,'n':len(genes),'weights':'all one; mean log2; post minus baseline','derivation':'Intersection of unambiguous canonical platform-gene universes GPL13158/GPL570/GPL6244; no validation expression/outcome-based gene choice','required_actual_coverage':'194/194 required; do not silently average a different subset','source_coverage_rule':'Original Hallmark200 coverage >=80% remains required and reported'}
v=lock['primary_validation']
v['mandatory_parallel_model']={'model':'delta_candidate ~ response + treatment_dose + delta_inflammatory_response','interpretation':'No own-baseline conditioning. Always present beside primary including estimate,95%CI,exactP; explanatory companion, not a second primary or fallback criterion.','primary_test_count_unchanged':True}
v['estimand']='ResponseYes conditional difference in paired candidate change at equal treatment dose, baseline candidate score and inflammation change. Response is observational, not randomized. Conditioning changes estimand; equivalent to post_score model with own baseline after algebraic parameter transformation.'
v['normalization_precheck']={'source':'GSE23597 metadata: GCOS1.4 global scaling to500; not documented RMA','rule':'Inspect finite matrix and source. For nonnegative matrix with99th percentile>100 apply log2(pmax(x,1)), report values floored. If99th percentile<=40 and minimum>=-20 retain deposited log scale and record numerical/source evidence. Other scales or negative high-intensity matrix trigger technical clarification, not outcome-driven choice. No repeat normalization.','scope':'Technical scale determination fixed before expression access; no outcome comparisons to choose transform'}
v['metadata_design_expectation']={'pairs':32,'responders':20,'nonresponders':12,'dose_sizes':{'Placebo':8,'IFX_5mgkg':10,'IFX_10mgkg':14},'metadata_rank':4,'full_model_expected_coefficients':6,'full_model_expected_residual_df':26,'full_model_leverage':'Unknown until expression covariates computed; report all patients and maximum, no leverage-based automatic removal'}
v['non_evaluable_rule']=v['non_evaluable_rule']+' Additionally all194 frozen common inflammatory genes must be present in actual matrix. No numeric leverage cutoff creates non-evaluability or outcome-based exclusion.'
lock['reference_program_rules']='Use canonicalized source membership, no feature selection from validation. Require >=80% original source-gene coverage; report measured/missing genes and cross-platform membership differences. Secondary reference tests use own baseline and frozen common194 inflammation covariate. BH across the three specified secondary tests with n=3 even if one is non-evaluable. No inference of superiority/equivalence from separate P values, FDR, or different-scale coefficients.'
lock['prior_score_limits']['IBrD']='No substantive IBrD comparison in these microarray analyses: incompatible feature coverage and original trained objects unavailable. Historical partial-score correlations retired and retained only for provenance. scRNA compatibility must be independently assessed before any future reproduction.'
lock['additional_validation_roles']['GSE73661']='Descriptive/supportive-only regardless of GSE23597 result. Never an alternative, rescue or replacement primary validation; no primary-test success may be declared from this cohort. Preserve source exposure paths and visit windows. Any later confirmatory question requires a separately labelled prospective protocol and new untouched data.'
lock['forbidden_claims']+=['Six-gene score superior to CT_Colonocytes based on discovery significance or overlap comparison','Six-gene score superior or equivalent to generic OXPHOS based on separate P/FDR values','Leave-one-gene-out stability proves absence of selection bias or overfitting','MARS coefficient attenuation equals a causally explained fraction','GSE73661 rescues or replaces failed GSE23597 primary validation','Complete IBrD comparison from a feature-incompatible partial proxy','Internal timestamp/hash freeze is a registered report or public preregistration']
inputs=['inputs/annotation/hgnc_complete_set_20260910.txt','inputs/annotation/GPL13158.annot.gz','inputs/annotation/GPL570.annot.gz','inputs/annotation/GPL6244.relay.annot.gz','runs/001D_annotation/program_scoring_membership.tsv','runs/001D_annotation/program_membership_canonical.tsv','runs/001D_annotation/frozen_common_inflammation_members.tsv','runs/001D_annotation/platform_program_coverage.tsv','runs/001D_annotation/program_scores.rds','provenance/reviews/002A_metadata_prevalidation_pairs_independent_v1.tsv','provenance/reviews/002A_metadata_prevalidation_independent_v1.json','code/annotation_001D.py','code/discovery_001D.R','renv.lock']
lock['amended_frozen_inputs']=[record(f) for f in inputs]
lock['coverage_threshold_timing']='Version1.0 >=80% source coverage retained; version1.1 fixes common194 inflammation covariate and100% coverage of that exact panel before validation expression. No threshold chosen from validation outcomes.'
for k in ['frozen_utc','source_code_commit','adoption_review']:lock.pop(k,None)
(P/'planning/signature_lock_v1.1.draft.json').write_text(json.dumps(lock,ensure_ascii=False,indent=2))
print('DRAFT_CREATED common',len(genes))
