options(stringsAsFactors=FALSE)
suppressPackageStartupMessages({library(data.table);library(ggplot2);library(jsonlite)})
root<-"/root/projects/UC_Treatment_Recovery";out<-file.path(root,"runs/001B_discovery")
rows<-rbindlist(lapply(c("primary_paired","barcode_sensitivity"),function(b)fread(file.path(out,b,"camera_Hallmark_all.tsv"))))
rows$direction_sign<-ifelse(rows$Direction=="Up",1,-1)
rows$signed_log10FDR<-rows$direction_sign*pmin(-log10(pmax(rows$FDR,1e-50)),12)
rows$term_label<-gsub("_"," ",rows$term)
rows$term_label<-factor(rows$term_label,levels=rev(sort(unique(rows$term_label))))
rows$contrast_label<-factor(rows$contrast,levels=c("GLM_change","Placebo_change","GLM_minus_Placebo","GLM_response_difference"),labels=c("GLM\nchange","Placebo\nchange","GLM minus\nplacebo","GLM response\nassociation"))
rows$branch_label<-factor(rows$branch,levels=c("primary_paired","barcode_sensitivity"),labels=c("Primary paired model","Inferred barcode sensitivity"))
p<-ggplot(rows,aes(contrast_label,term_label,fill=signed_log10FDR))+geom_tile(color="white",linewidth=.2)+geom_point(data=rows[FDR<.05],size=.75,shape=16)+facet_grid(.~branch_label)+scale_fill_gradient2(low="#2166AC",mid="white",high="#B2182B",limits=c(-12,12),name="Signed -log10(FDR)\n(capped at 12)")+labs(title="Exploratory Hallmark program screen",subtitle="CAMERA competitive tests; dots: FDR < 0.05 within each contrast\nDirection is relative to background genes, not measured pathway activity",x=NULL,y=NULL)+theme_minimal(base_size=10,base_family="sans")+theme(panel.grid=element_blank(),axis.text.y=element_text(size=7.3),axis.text.x=element_text(size=8),strip.text=element_text(face="bold"),legend.position="bottom",plot.title=element_text(face="bold"))
ggsave(file.path(out,"Exploratory01_All_Hallmark.pdf"),p,width=10,height=12,device=cairo_pdf)
ggsave(file.path(out,"Exploratory01_All_Hallmark.png"),p,width=10,height=12,dpi=150)
fwrite(rows,file.path(out,"Exploratory01_All_Hallmark_source.tsv"),sep="\t")
ip<-installed.packages()
write.table(ip[,c("Package","Version","LibPath","Built")],file.path(root,"provenance/environments/installed_R_packages.tsv"),sep="\t",row.names=FALSE,quote=FALSE)
cat("Exploratory overview written\n")
