options(stringsAsFactors=FALSE);suppressPackageStartupMessages({library(data.table);library(ggplot2)})
setwd("/root/projects/UC_Treatment_Recovery");figdir<-"runs/002B_figures";dir.create(figdir,showWarnings=FALSE,recursive=TRUE);source("code/figure_theme.R")
a<-fread("runs/002B_precision/conditional_power_scenarios.tsv")
a$cohort<-factor(a$cohort,levels=c("GSE92415","GSE23597"))
fwrite(a,file.path(figdir,"Fig002B01_ConditionalPrecision_source.tsv"),sep="\t")
p<-ggplot(a,aes(assumed_true_effect,power*100,color=cohort))+geom_hline(yintercept=80,linetype=2,color="grey65")+geom_vline(xintercept=.5994069273,linetype=3,color="grey65")+geom_line(linewidth=.85)+scale_color_manual(values=c("#2166AC","#B35806"))+scale_y_continuous(limits=c(0,100),breaks=seq(0,100,20))+labs(title="Conditional precision scenarios",subtitle="Two-sided rejection probability using fixed observed designs and plug-in residual SD",x="Assumed true effect (mean log2 score difference)",y="Conditional rejection probability (%)",color=NULL,caption="These curves are assumption-based sensitivity analyses, not known true power.\nThe discovery estimate may be optimistic; observed power does not explain a nonsignificant result.")+theme_project()+theme(plot.caption=element_text(hjust=0,size=9))
save_panel(p,"Fig002B01_ConditionalPrecision",8.5,6)
e<-fread("runs/002B_GSE73661_support/candidate_support_models.tsv")
e$model<-factor(e$model,levels=c("parallel_no_inflammation","parallel_no_baseline","adjusted_support"),labels=c("Without inflammation","Without own baseline","Baseline + inflammation"))
fwrite(e,file.path(figdir,"Fig002B02_EndoscopicSupport_source.tsv"),sep="\t")
q<-ggplot(e,aes(estimate,model,color=method))+geom_vline(xintercept=0,linetype=2,color="grey65")+geom_errorbar(aes(xmin=lower,xmax=upper),orientation="y",position=position_dodge(width=.4),width=.13,linewidth=.65)+geom_point(position=position_dodge(width=.4),size=2.5)+scale_color_manual(values=c("OLS"="#1B7837","HC3"="#762A83"))+labs(title="GSE73661: association with endoscopic healing",subtitle="23 IFX-treated patients; W0 to source-reported W4/6",x="HealingYes coefficient (mean log2 score change)",y=NULL,color=NULL,caption="Prespecified for descriptive support after GSE23597 results were known.\nThis analysis does not replace the GSE23597 primary test; no pooled P value is calculated.")+theme_project()+theme(plot.caption=element_text(hjust=0,size=9))
save_panel(q,"Fig002B02_EndoscopicSupport",8.8,5.5)
cat("002B_FIGURES_COMPLETE\n")
